"""Added distance_account table

Revision ID: 23a4cfad31a3
Revises: 43e65aff739e
Create Date: 2026-10-03 19:02:46.829088

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "23a4cfad31a3"
down_revision = "43e65aff739e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distance_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fitbit_user_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("credit_km", sa.Float(), nullable=True),
        sa.Column("debit_km", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fitbit_user_id"], ["fitbit_users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fitbit_user_id", "type_id", "date"),
    )
    with op.batch_alter_table("distance_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_distance_account_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("distance_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_distance_account_id"))

    op.drop_table("distance_account")
    # ### end Alembic commands ###
